/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author rivar
 */
public class Inicio extends javax.swing.JPanel {

    /**
     * Creates new form Inicio
     */
    ImageIcon icon;
    JPanel pnlContenedorImagen;

    public Inicio() {
        initComponents();
        pnlContenedorImagen = new JPanel();
        pnlContenedorImagen.setBounds(50, 50, 30, 40);
        cargarImagen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cargarImagen() {
        icon = new ImageIcon("gui.imgs/foto pol.jpg");
        Image img = icon.getImage();
        int alto = img.getHeight(pnlContenedorImagen);
        int ancho = img.getWidth(pnlContenedorImagen);

        System.out.println(ancho + " " + alto);

        JLabel lbl = new JLabel();
        lbl.setIcon(icon);
        pnlContenedorImagen.add(lbl);
        lbl.setBounds(5, 5, ancho, alto);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
