/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import dao.EsculturasDAO;
import dao.ObrasDAO;
import dao.PinturasDAO;
import entidades.Escultura;
import entidades.Obras;
import entidades.Pintura;
import java.awt.Color;
import java.sql.SQLException;
import java.util.List;
import javax.swing.border.LineBorder;

/**
 *
 * @author rivar
 */
public class PanelGral extends javax.swing.JPanel {

    ObrasDAO pinturas = new PinturasDAO();
    ObrasDAO esculturas = new EsculturasDAO();

    public PanelGral() {
        initComponents();

        lbID1.setVisible(false);
        txtID.setVisible(false);
        lbIDEscu.setVisible(false);
        txtIDEscu.setVisible(false);
        btnBuscarEscultura.setVisible(false);
        btnEliminarEscultura.setVisible(false);
        txtEncontrado.setVisible(false);
        btnEliminarPintura.setVisible(false);
        btnBuscarPintura.setVisible(false);
        txtEncontrado1.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMostrarTodo = new javax.swing.JTextArea();
        btnMostrar = new javax.swing.JButton();
        panelEscultura = new javax.swing.JPanel();
        btnGuardarEscu = new javax.swing.JButton();
        btnEliminarEscu = new javax.swing.JButton();
        btnBuscarEscu = new javax.swing.JButton();
        lbNombreEscu = new javax.swing.JLabel();
        lbArtistaEscu = new javax.swing.JLabel();
        lbMateriales = new javax.swing.JLabel();
        lbIDEscu = new javax.swing.JLabel();
        txtNombreEscu = new javax.swing.JTextField();
        txtArtistaEscu = new javax.swing.JTextField();
        txtMateriales = new javax.swing.JTextField();
        txtIDEscu = new javax.swing.JTextField();
        btnGuardarEscultura = new javax.swing.JButton();
        btnEliminarEscultura = new javax.swing.JButton();
        btnBuscarEscultura = new javax.swing.JButton();
        txtEncontrado = new javax.swing.JTextArea();
        panelGuardar = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        lbNombre = new javax.swing.JLabel();
        lbArtista = new javax.swing.JLabel();
        lbColores = new javax.swing.JLabel();
        lbID1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtArtista = new javax.swing.JTextField();
        txtColores = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        btnGuardarPintura = new javax.swing.JButton();
        btnEliminarPintura = new javax.swing.JButton();
        btnBuscarPintura = new javax.swing.JButton();
        txtEncontrado1 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(0, 0, 0));

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 0));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Swis721 Hv BT", 0, 12)); // NOI18N
        jTabbedPane1.setMaximumSize(new java.awt.Dimension(370, 26));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(370, 26));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(370, 26));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "STOCK", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tw Cen MT Condensed", 1, 48), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtMostrarTodo.setColumns(20);
        txtMostrarTodo.setFont(new java.awt.Font("Swis721 Hv BT", 0, 18)); // NOI18N
        txtMostrarTodo.setRows(5);
        txtMostrarTodo.setMaximumSize(new java.awt.Dimension(504, 504));
        jScrollPane1.setViewportView(txtMostrarTodo);

        btnMostrar.setFont(new java.awt.Font("Swis721 Hv BT", 0, 18)); // NOI18N
        btnMostrar.setText("Mostrar todas las obras");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(588, 588, 588)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMostrar)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(483, 483, 483))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(btnMostrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mostrar Todo", jPanel2);

        panelEscultura.setBackground(new java.awt.Color(0, 0, 0));
        panelEscultura.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ESCULTURAS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tw Cen MT Condensed", 1, 48), new java.awt.Color(255, 255, 255))); // NOI18N
        panelEscultura.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnGuardarEscu.setFont(new java.awt.Font("Swis721 Hv BT", 0, 18)); // NOI18N
        btnGuardarEscu.setText("Guardar");
        btnGuardarEscu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarEscuActionPerformed(evt);
            }
        });

        btnEliminarEscu.setFont(new java.awt.Font("Swis721 Hv BT", 0, 18)); // NOI18N
        btnEliminarEscu.setText("Eliminar");
        btnEliminarEscu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEscuActionPerformed(evt);
            }
        });

        btnBuscarEscu.setFont(new java.awt.Font("Swis721 Hv BT", 0, 18)); // NOI18N
        btnBuscarEscu.setText("Buscar");
        btnBuscarEscu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEscuActionPerformed(evt);
            }
        });

        lbNombreEscu.setFont(new java.awt.Font("Swis721 Hv BT", 0, 18)); // NOI18N
        lbNombreEscu.setForeground(new java.awt.Color(255, 255, 255));
        lbNombreEscu.setText("Nombre");
        lbNombreEscu.setMaximumSize(new java.awt.Dimension(266, 26));
        lbNombreEscu.setMinimumSize(new java.awt.Dimension(266, 26));

        lbArtistaEscu.setFont(new java.awt.Font("Swis721 Hv BT", 0, 18)); // NOI18N
        lbArtistaEscu.setForeground(new java.awt.Color(255, 255, 255));
        lbArtistaEscu.setText("Artista");
        lbArtistaEscu.setMaximumSize(new java.awt.Dimension(266, 26));
        lbArtistaEscu.setMinimumSize(new java.awt.Dimension(266, 26));

        lbMateriales.setFont(new java.awt.Font("Swis721 Hv BT", 0, 18)); // NOI18N
        lbMateriales.setForeground(new java.awt.Color(255, 255, 255));
        lbMateriales.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbMateriales.setText("Materiales ");
        lbMateriales.setMaximumSize(new java.awt.Dimension(266, 26));
        lbMateriales.setMinimumSize(new java.awt.Dimension(266, 26));
        lbMateriales.setPreferredSize(new java.awt.Dimension(70, 20));

        lbIDEscu.setFont(new java.awt.Font("Swis721 Hv BT", 0, 18)); // NOI18N
        lbIDEscu.setForeground(new java.awt.Color(255, 255, 255));
        lbIDEscu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbIDEscu.setText("ID");
        lbIDEscu.setMaximumSize(new java.awt.Dimension(266, 26));
        lbIDEscu.setMinimumSize(new java.awt.Dimension(266, 26));

        txtNombreEscu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNombreEscu.setMaximumSize(new java.awt.Dimension(370, 26));
        txtNombreEscu.setMinimumSize(new java.awt.Dimension(370, 26));
        txtNombreEscu.setPreferredSize(new java.awt.Dimension(370, 26));

        txtArtistaEscu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtMateriales.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMateriales.setMinimumSize(new java.awt.Dimension(400, 26));

        txtIDEscu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnGuardarEscultura.setFont(new java.awt.Font("Swis721 Hv BT", 0, 18)); // NOI18N
        btnGuardarEscultura.setText("Guardar escultura");
        btnGuardarEscultura.setMaximumSize(new java.awt.Dimension(370, 26));
        btnGuardarEscultura.setMinimumSize(new java.awt.Dimension(370, 26));
        btnGuardarEscultura.setPreferredSize(new java.awt.Dimension(370, 26));
        btnGuardarEscultura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarEsculturaActionPerformed(evt);
            }
        });

        btnEliminarEscultura.setFont(new java.awt.Font("Swis721 Hv BT", 0, 18)); // NOI18N
        btnEliminarEscultura.setText("Eliminar escultura");
        btnEliminarEscultura.setMaximumSize(new java.awt.Dimension(370, 26));
        btnEliminarEscultura.setMinimumSize(new java.awt.Dimension(370, 26));
        btnEliminarEscultura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEsculturaActionPerformed(evt);
            }
        });

        btnBuscarEscultura.setFont(new java.awt.Font("Swis721 Hv BT", 0, 18)); // NOI18N
        btnBuscarEscultura.setText("Buscar escultura");
        btnBuscarEscultura.setMaximumSize(new java.awt.Dimension(370, 26));
        btnBuscarEscultura.setMinimumSize(new java.awt.Dimension(370, 26));
        btnBuscarEscultura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEsculturaActionPerformed(evt);
            }
        });

        txtEncontrado.setColumns(20);
        txtEncontrado.setFont(new java.awt.Font("Swis721 Hv BT", 0, 14)); // NOI18N
        txtEncontrado.setRows(5);
        txtEncontrado.setMaximumSize(new java.awt.Dimension(400, 26));
        txtEncontrado.setMinimumSize(new java.awt.Dimension(400, 26));

        javax.swing.GroupLayout panelEsculturaLayout = new javax.swing.GroupLayout(panelEscultura);
        panelEscultura.setLayout(panelEsculturaLayout);
        panelEsculturaLayout.setHorizontalGroup(
            panelEsculturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEsculturaLayout.createSequentialGroup()
                .addGroup(panelEsculturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelEsculturaLayout.createSequentialGroup()
                        .addGap(464, 464, 464)
                        .addGroup(panelEsculturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbArtistaEscu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbIDEscu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbMateriales, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbNombreEscu, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))
                        .addGroup(panelEsculturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelEsculturaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                .addGroup(panelEsculturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEsculturaLayout.createSequentialGroup()
                                        .addComponent(btnGuardarEscu)
                                        .addGap(34, 34, 34)
                                        .addComponent(btnEliminarEscu)
                                        .addGap(34, 34, 34)
                                        .addComponent(btnBuscarEscu))
                                    .addComponent(txtArtistaEscu, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtNombreEscu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)))
                            .addGroup(panelEsculturaLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(panelEsculturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMateriales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtIDEscu)))))
                    .addGroup(panelEsculturaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelEsculturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelEsculturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnGuardarEscultura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                                .addComponent(btnEliminarEscultura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBuscarEscultura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtEncontrado, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(745, 745, 745))
        );
        panelEsculturaLayout.setVerticalGroup(
            panelEsculturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEsculturaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelEsculturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarEscu)
                    .addComponent(btnEliminarEscu)
                    .addComponent(btnBuscarEscu))
                .addGap(46, 46, 46)
                .addGroup(panelEsculturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombreEscu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreEscu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEsculturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbArtistaEscu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtArtistaEscu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEsculturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMateriales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMateriales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(panelEsculturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIDEscu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIDEscu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGuardarEscultura, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminarEscultura, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarEscultura, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEncontrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Escultura", panelEscultura);

        panelGuardar.setBackground(new java.awt.Color(0, 0, 0));
        panelGuardar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PINTURAS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tw Cen MT Condensed", 1, 48), new java.awt.Color(255, 255, 255))); // NOI18N
        panelGuardar.setForeground(new java.awt.Color(255, 255, 255));
        panelGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelGuardar.setFont(new java.awt.Font("Swis721 Hv BT", 0, 12)); // NOI18N

        btnGuardar.setFont(new java.awt.Font("Swis721 Hv BT", 0, 18)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Swis721 Hv BT", 0, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setAlignmentX(4.0F);
        btnEliminar.setFocusable(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Swis721 Hv BT", 0, 18)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lbNombre.setFont(new java.awt.Font("Swis721 Hv BT", 0, 18)); // NOI18N
        lbNombre.setForeground(new java.awt.Color(255, 255, 255));
        lbNombre.setText("Nombre");
        lbNombre.setMaximumSize(new java.awt.Dimension(266, 26));
        lbNombre.setMinimumSize(new java.awt.Dimension(266, 26));

        lbArtista.setFont(new java.awt.Font("Swis721 Hv BT", 0, 18)); // NOI18N
        lbArtista.setForeground(new java.awt.Color(255, 255, 255));
        lbArtista.setText("Artista");
        lbArtista.setMaximumSize(new java.awt.Dimension(266, 26));
        lbArtista.setMinimumSize(new java.awt.Dimension(266, 26));

        lbColores.setFont(new java.awt.Font("Swis721 Hv BT", 0, 18)); // NOI18N
        lbColores.setForeground(new java.awt.Color(255, 255, 255));
        lbColores.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbColores.setText("Colores");
        lbColores.setMaximumSize(new java.awt.Dimension(266, 26));
        lbColores.setMinimumSize(new java.awt.Dimension(266, 26));

        lbID1.setFont(new java.awt.Font("Swis721 Hv BT", 0, 18)); // NOI18N
        lbID1.setForeground(new java.awt.Color(255, 255, 255));
        lbID1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbID1.setText("ID");
        lbID1.setMaximumSize(new java.awt.Dimension(266, 26));
        lbID1.setMinimumSize(new java.awt.Dimension(266, 26));

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNombre.setMaximumSize(new java.awt.Dimension(370, 26));
        txtNombre.setMinimumSize(new java.awt.Dimension(370, 26));
        txtNombre.setPreferredSize(new java.awt.Dimension(370, 26));

        txtArtista.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtArtista.setMaximumSize(new java.awt.Dimension(370, 26));
        txtArtista.setMinimumSize(new java.awt.Dimension(370, 26));
        txtArtista.setPreferredSize(new java.awt.Dimension(370, 26));

        txtColores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtColores.setMaximumSize(new java.awt.Dimension(370, 26));
        txtColores.setMinimumSize(new java.awt.Dimension(370, 26));
        txtColores.setPreferredSize(new java.awt.Dimension(370, 26));

        txtID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtID.setMaximumSize(new java.awt.Dimension(370, 26));
        txtID.setMinimumSize(new java.awt.Dimension(370, 26));
        txtID.setPreferredSize(new java.awt.Dimension(370, 26));

        btnGuardarPintura.setFont(new java.awt.Font("Swis721 Hv BT", 0, 18)); // NOI18N
        btnGuardarPintura.setText("Guardar escultura");
        btnGuardarPintura.setMaximumSize(new java.awt.Dimension(370, 26));
        btnGuardarPintura.setMinimumSize(new java.awt.Dimension(370, 26));
        btnGuardarPintura.setPreferredSize(new java.awt.Dimension(370, 26));
        btnGuardarPintura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPinturaActionPerformed(evt);
            }
        });

        btnEliminarPintura.setFont(new java.awt.Font("Swis721 Hv BT", 0, 18)); // NOI18N
        btnEliminarPintura.setText("Eliminar escultura");
        btnEliminarPintura.setMaximumSize(new java.awt.Dimension(370, 26));
        btnEliminarPintura.setMinimumSize(new java.awt.Dimension(370, 26));
        btnEliminarPintura.setPreferredSize(new java.awt.Dimension(370, 26));
        btnEliminarPintura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPinturaActionPerformed(evt);
            }
        });

        btnBuscarPintura.setFont(new java.awt.Font("Swis721 Hv BT", 0, 18)); // NOI18N
        btnBuscarPintura.setText("Buscar escultura");
        btnBuscarPintura.setMaximumSize(new java.awt.Dimension(370, 26));
        btnBuscarPintura.setMinimumSize(new java.awt.Dimension(370, 26));
        btnBuscarPintura.setPreferredSize(new java.awt.Dimension(370, 26));
        btnBuscarPintura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPinturaActionPerformed(evt);
            }
        });

        txtEncontrado1.setColumns(20);
        txtEncontrado1.setFont(new java.awt.Font("Swis721 Hv BT", 0, 14)); // NOI18N
        txtEncontrado1.setRows(5);
        txtEncontrado1.setMaximumSize(new java.awt.Dimension(400, 26));
        txtEncontrado1.setMinimumSize(new java.awt.Dimension(400, 26));

        javax.swing.GroupLayout panelGuardarLayout = new javax.swing.GroupLayout(panelGuardar);
        panelGuardar.setLayout(panelGuardarLayout);
        panelGuardarLayout.setHorizontalGroup(
            panelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGuardarLayout.createSequentialGroup()
                .addGap(464, 464, 464)
                .addGroup(panelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelGuardarLayout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addGap(34, 34, 34)
                        .addComponent(btnEliminar)
                        .addGap(34, 34, 34)
                        .addComponent(btnBuscar))
                    .addGroup(panelGuardarLayout.createSequentialGroup()
                        .addGroup(panelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbArtista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                            .addComponent(lbID1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbColores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtArtista, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(txtColores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGuardarPintura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminarPintura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBuscarPintura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(txtEncontrado1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGuardarLayout.setVerticalGroup(
            panelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGuardarLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnEliminar)
                    .addComponent(btnBuscar))
                .addGap(46, 46, 46)
                .addGroup(panelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbColores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtColores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(panelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGuardarPintura, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminarPintura, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarPintura, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEncontrado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pintura", panelGuardar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        List<Pintura> listaP = pinturas.listarObras();
        List<Escultura> listaE = esculturas.listarObras();
        txtMostrarTodo.setText("");

        for (Pintura i : listaP) {
            txtMostrarTodo.append(i.toString());
        }
        for (Escultura i : listaE) {
            txtMostrarTodo.append(i.toString());
        }


    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnBuscarEsculturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEsculturaActionPerformed
        Obras escultura = (Escultura) esculturas.buscarObra(Integer.parseInt(txtIDEscu.getText()));
        if (escultura != null) {
            txtEncontrado.setText(escultura.toString());
        } else {
            txtEncontrado.setText("No se han encontrado resultados...");
        }
        txtIDEscu.setText("");
    }//GEN-LAST:event_btnBuscarEsculturaActionPerformed

    private void btnEliminarEsculturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEsculturaActionPerformed
        esculturas.eliminar(Integer.parseInt(txtIDEscu.getText()));
        txtIDEscu.setText("");
    }//GEN-LAST:event_btnEliminarEsculturaActionPerformed

    private void btnGuardarEsculturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarEsculturaActionPerformed
        try {
            Obras escultura = new Escultura(txtNombreEscu.getText(), Integer.parseInt(txtMateriales.getText()), txtArtistaEscu.getText());
            esculturas.registrar(escultura);
            txtNombreEscu.setText("");
            txtArtistaEscu.setText("");
            txtMateriales.setText("");
        } catch (Exception e) {
            System.out.println(e);
            txtMateriales.setText("Ingrese numeros porfavor!");
        }
    }//GEN-LAST:event_btnGuardarEsculturaActionPerformed

    private void btnBuscarEscuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEscuActionPerformed
        lbNombreEscu.setVisible(false);
        txtNombreEscu.setVisible(false);
        lbArtistaEscu.setVisible(false);
        txtArtistaEscu.setVisible(false);
        txtMateriales.setVisible(false);
        lbMateriales.setVisible(false);
        lbIDEscu.setVisible(true);
        txtIDEscu.setVisible(true);
        btnBuscarEscultura.setVisible(true);
        btnGuardarEscultura.setVisible(false);
        btnEliminarEscultura.setVisible(false);
        txtEncontrado.setVisible(true);
    }//GEN-LAST:event_btnBuscarEscuActionPerformed

    private void btnEliminarEscuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEscuActionPerformed
        lbNombreEscu.setVisible(false);
        txtNombreEscu.setVisible(false);
        lbArtistaEscu.setVisible(false);
        txtArtistaEscu.setVisible(false);
        txtMateriales.setVisible(false);
        lbMateriales.setVisible(false);
        lbIDEscu.setVisible(true);
        txtIDEscu.setVisible(true);
        btnBuscarEscultura.setVisible(false);
        btnGuardarEscultura.setVisible(false);
        btnEliminarEscultura.setVisible(true);
        txtEncontrado.setVisible(false);
    }//GEN-LAST:event_btnEliminarEscuActionPerformed

    private void btnGuardarEscuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarEscuActionPerformed
        lbNombreEscu.setVisible(true);
        txtNombreEscu.setVisible(true);
        lbArtistaEscu.setVisible(true);
        txtArtistaEscu.setVisible(true);
        txtMateriales.setVisible(true);
        lbMateriales.setVisible(true);
        lbIDEscu.setVisible(false);
        txtIDEscu.setVisible(false);
        btnBuscarEscultura.setVisible(false);
        btnGuardarEscultura.setVisible(true);
        btnEliminarEscultura.setVisible(false);
        txtEncontrado.setVisible(false);
    }//GEN-LAST:event_btnGuardarEscuActionPerformed

    private void btnBuscarPinturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPinturaActionPerformed
        Obras pintura = (Pintura) pinturas.buscarObra(Integer.parseInt(txtID.getText()));
        if (pintura != null) {
            txtEncontrado1.setText(pintura.toString());
        } else {
            txtEncontrado1.setText("No se han encontrado resultados...");
        }
        txtID.setText("");
    }//GEN-LAST:event_btnBuscarPinturaActionPerformed

    private void btnEliminarPinturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPinturaActionPerformed
        pinturas.eliminar(Integer.parseInt(txtID.getText()));
        txtID.setText("");
    }//GEN-LAST:event_btnEliminarPinturaActionPerformed

    private void btnGuardarPinturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPinturaActionPerformed
        try {
            Obras pintura = new Pintura(txtNombre.getText(), Integer.parseInt(txtColores.getText()), txtArtista.getText());
            pinturas.registrar(pintura);
            txtNombre.setText("");
            txtArtista.setText("");
            txtColores.setText("");
        } catch (Exception e) {
            System.out.println(e);
            txtColores.setText("Ingrese numeros porfavor!");
        }
    }//GEN-LAST:event_btnGuardarPinturaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        lbNombre.setVisible(false);
        txtNombre.setVisible(false);
        lbArtista.setVisible(false);
        txtArtista.setVisible(false);
        lbColores.setVisible(false);
        txtColores.setVisible(false);
        lbID1.setVisible(true);
        txtID.setVisible(true);
        btnBuscarPintura.setVisible(true);
        btnGuardarPintura.setVisible(false);
        btnEliminarPintura.setVisible(false);
        txtEncontrado1.setVisible(true);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        lbNombre.setVisible(false);
        txtNombre.setVisible(false);
        lbArtista.setVisible(false);
        txtArtista.setVisible(false);
        lbColores.setVisible(false);
        txtColores.setVisible(false);
        lbID1.setVisible(true);
        txtID.setVisible(true);
        btnBuscarPintura.setVisible(false);
        btnGuardarPintura.setVisible(false);
        btnEliminarPintura.setVisible(true);
        txtEncontrado1.setVisible(false);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        lbNombre.setVisible(true);
        txtNombre.setVisible(true);
        lbArtista.setVisible(true);
        txtArtista.setVisible(true);
        lbColores.setVisible(true);
        txtColores.setVisible(true);
        lbID1.setVisible(false);
        txtID.setVisible(false);
        btnBuscarPintura.setVisible(false);
        btnGuardarPintura.setVisible(true);
        btnEliminarPintura.setVisible(false);
        txtEncontrado1.setVisible(false);
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarEscu;
    private javax.swing.JButton btnBuscarEscultura;
    private javax.swing.JButton btnBuscarPintura;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarEscu;
    private javax.swing.JButton btnEliminarEscultura;
    private javax.swing.JButton btnEliminarPintura;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnGuardarEscu;
    private javax.swing.JButton btnGuardarEscultura;
    private javax.swing.JButton btnGuardarPintura;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbArtista;
    private javax.swing.JLabel lbArtistaEscu;
    private javax.swing.JLabel lbColores;
    private javax.swing.JLabel lbID1;
    private javax.swing.JLabel lbIDEscu;
    private javax.swing.JLabel lbMateriales;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbNombreEscu;
    private javax.swing.JPanel panelEscultura;
    private javax.swing.JPanel panelGuardar;
    private javax.swing.JTextField txtArtista;
    private javax.swing.JTextField txtArtistaEscu;
    private javax.swing.JTextField txtColores;
    private javax.swing.JTextArea txtEncontrado;
    private javax.swing.JTextArea txtEncontrado1;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtIDEscu;
    private javax.swing.JTextField txtMateriales;
    private javax.swing.JTextArea txtMostrarTodo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreEscu;
    // End of variables declaration//GEN-END:variables
}
